name: "main"

on:
  push:
    branches:
      - main

env:
  GOOGLE_REGION: us-east1
  ARTIFACT_REGISTRY: us-east1-docker.pkg.dev/candidates-358318/devonrobinson-ops-0be6
  CLOUD_RUN: devonrobinson-ops-0be6
  CLOUD_RUN_URL: https://devonrobinson-ops-0be6-ojiebjit6q-ue.a.run.app

jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest

    
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      
      # This step is needed to authenticate our creds to build our app
      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v0
      
      # We use this git action to build our app via our Dockerfile and docker-compose, we pass in creds here via env variables 
      - name: Configure Docker Client
        shell: bash
        run: gcloud --quiet auth configure-docker us-east1-docker.pkg.dev

      - name: Build and Push 
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: "${{ env.ARTIFACT_REGISTRY }}/helloworld:latest"
        
      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "${{ env.CLOUD_RUN }}" \
            --quiet \
            --region "us-east1" \
            --image "${{ env.ARTIFACT_REGISTRY }}/helloworld:latest" 